export const LOG_IN_SUCCESS = "LOG_IN_SUCCESS";
export const AJAX_CALL_IN_PROGRESS = "AJAX_CALL_IN_PROGRESS";
export const AJAX_CALL_FINISHED = "AJAX_CALL_FINISHED";
export const USER_FETCH_SUCCESS = "USER_FETCH_SUCCESS";
export const SEARCH_RESULT_SUCCESS = "SEARCH_RESULT_SUCCESS";
export const FETCH_FORKS_LIST_SUCCESS = "FETCH_FORKS_LIST_SUCCESS";
export const FETCH_ISSUES_LIST_SUCCESS = "FETCH_ISSUES_LIST_SUCCESS";
export const FORK_REPO_SUCCESS = "FORK_REPO_SUCCESS";
